/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.Session;
import config.display;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import library.LoginForm;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hp
 */
public class borrow extends javax.swing.JFrame {

    

    /**
     * Creates new form ADD
     */
    public borrow() {
        initComponents();
        setTitle("LIBRARY");
        displayData();
    }

    public void displayData() {
    try {
        Session sess = Session.getInstance();
        int userID = sess.getId();
        Connection connection = display.getConnection();
        if (connection != null) {
            String query = 
                "SELECT b.book_id, b.ISBN, b.book_name, b.author, b.publisher, " +
                "CASE " +
                "   WHEN br.status = 'Borrowed' THEN 'Borrowed' " +
                "   WHEN br.status = 'Pending' THEN 'Pending' " +
                "   ELSE 'Available' " +
                "END AS status " +
                "FROM books b " +
                "LEFT JOIN borrowings br ON b.book_id = br.book_id AND br.u_id = ? " +
                "WHERE b.quantity > 0";
                
            PreparedStatement pstmt = connection.prepareStatement(query);
            pstmt.setInt(1, userID);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs != null) {
                table.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
            } else {
                JOptionPane.showMessageDialog(this, "No data found in the database.");
            }
            
            pstmt.close();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to establish a connection to the database.");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error fetching data from database: " + ex.getMessage());
        ex.printStackTrace();
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        searchs = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        borrow = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/male_user_50px.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Home_26px_2.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, 30));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Welcome to Library ");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 710, 50));

        label2.setBackground(new java.awt.Color(0, 0, 0));
        label2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
        });
        jPanel5.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 110, 70));

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 0, 780, 70);

        table.setGridColor(new java.awt.Color(153, 0, 0));
        jScrollPane1.setViewportView(table);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 730, 360);

        searchs.setText("Input Here");
        searchs.setBorder(null);
        searchs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchsMouseClicked(evt);
            }
        });
        jPanel3.add(searchs);
        searchs.setBounds(550, 90, 180, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel11);
        jLabel11.setBounds(730, 80, 50, 50);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(550, 120, 180, 10);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4);
        jLabel4.setBounds(520, 90, 23, 40);

        borrow.setBackground(new java.awt.Color(153, 0, 0));
        borrow.setText("BORROW");
        borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowActionPerformed(evt);
            }
        });
        jPanel3.add(borrow);
        borrow.setBounds(20, 90, 90, 30);

        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        date.setName(""); // NOI18N
        jPanel3.add(date);
        date.setBounds(120, 90, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Select Date to Return");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(120, 74, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        userdashboard dash = new userdashboard();
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked
   
    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked

    }//GEN-LAST:event_label2MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         Session sess = Session.getInstance();
        
        if(sess.getId() == 0){
            JOptionPane.showMessageDialog(null, "No Account, Login First!");
            LoginForm lg = new LoginForm();
            lg.setVisible(true);
            this.dispose();
        }else{
        label2.setText(""+sess.getFname());
       
        } 
    }//GEN-LAST:event_formWindowActivated

    private void searchsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchsMouseClicked
        searchs.setText("");
    }//GEN-LAST:event_searchsMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        try {
            String searchTerm = searchs.getText().trim();
            if (!searchTerm.isEmpty() && !searchTerm.equals("Input Here")) {
                Connection connection = display.getConnection();
            if (connection != null) {
                String query = "SELECT book_id, book_name, ISBN, author, Publisher, quantity FROM books WHERE book_id LIKE ? OR book_name LIKE ? OR ISBN LIKE ? OR author LIKE ? OR Publisher LIKE ?  OR quantity LIKE ?";
                PreparedStatement pstmt = connection.prepareStatement(query);
                String likeTerm = "%" + searchTerm + "%";
            for (int i = 1; i <= 6; i++) {
                pstmt.setString(i, likeTerm);
            }
            ResultSet rs = pstmt.executeQuery();

            if (rs != null) {
                table.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
            } else {
                JOptionPane.showMessageDialog(this, "No matching books found.");
            }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to establish a connection to the database.");
            }
            } else {
                JOptionPane.showMessageDialog(this, "Please enter a search term.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error fetching search results: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        displayData();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void borrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowActionPerformed
          int selectedRow = table.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a book to borrow.");
        return;
    }
    try {
        int bookId = (int) table.getValueAt(selectedRow, 0);
        java.util.Date utilReturnDate = date.getDate();
        if (utilReturnDate == null) {
            JOptionPane.showMessageDialog(this, "Please select a return date.");
            return;
        }

        LocalDate localReturnDate = utilReturnDate.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        Date ReturnDate = Date.valueOf(localReturnDate);
        Date BorrowDate = Date.valueOf(LocalDate.now()); 
        
        Session sess = Session.getInstance();
        int userID = sess.getId();
        Connection connection = display.getConnection();
        if (connection != null) {
            String checkQuery = "SELECT * FROM borrowings WHERE book_id = ? AND u_id = ? AND status = ?";
            PreparedStatement checkPstmt = connection.prepareStatement(checkQuery);
            checkPstmt.setInt(1, bookId);
            checkPstmt.setInt(2, userID);
            checkPstmt.setString(3, "Pending");
            ResultSet checkRs = checkPstmt.executeQuery();

            if (checkRs.next()) {
                JOptionPane.showMessageDialog(this, "You have already requested to borrow this book.");
            } else {
                String borrowQuery = "INSERT INTO borrowings (book_id, u_id, borrow_date, return_date, status) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement borrowPstmt = connection.prepareStatement(borrowQuery);
                borrowPstmt.setInt(1, bookId);
                borrowPstmt.setInt(2, userID);
                borrowPstmt.setDate(3, BorrowDate); 
                borrowPstmt.setDate(4, ReturnDate);
                borrowPstmt.setString(5, "Pending"); 
                borrowPstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Borrow request submitted successfully!");
            }
            checkRs.close();
            checkPstmt.close();
            connection.close();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to establish a connection to the database.");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error borrowing book: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_borrowActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new borrow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrow;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel label2;
    private javax.swing.JTextField searchs;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
