/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static library.registerForm.email;
import static library.registerForm.uname;

/**
 *
 * @author Hp
 */
public class user extends javax.swing.JFrame {

    String Action;

    /**
     * Creates new form adduser
     */
    public user() {
        initComponents();
    }
    
    public void close(){              
        viewusers ad = new viewusers();
        ad.setVisible(true);
        this.dispose();
    }
    
    public boolean duplicateCheck(){
        dbConnector dbc = new dbConnector();
        
        try{
             String query = "SELECT * FROM tbl WHERE (u_username = '" + us.getText() + "' OR u_email = '" +em.getText()+ "') And u_id != '" +id .getText()+ "' " ;
        ResultSet resultSet = dbc.getData(query);
        
        if(resultSet.next()){
            email = resultSet.getString("u_email");
            if (email.equals(em.getText())) {
                JOptionPane.showMessageDialog(null, "Email already exists! Please use a different one.");   
                em.setText("");
            }
            uname = resultSet.getString("u_username");
            if (uname.equals(us.getText())) {
                JOptionPane.showMessageDialog(null, "Username already exists! Please choose a different one."); 
                 us.setText("");
            }
            return true;
        }else{
            return false;
        }
        
        } catch (SQLException ex) {
            System.out.println(""+ex);
        return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        nums = new javax.swing.JTextField();
        us = new javax.swing.JTextField();
        ps = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        label = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        stat = new javax.swing.JLabel();
        stats = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Home_26px_2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 490, 30, 70);
        jPanel1.add(fn);
        fn.setBounds(160, 80, 250, 40);
        jPanel1.add(ln);
        ln.setBounds(160, 130, 250, 40);
        jPanel1.add(em);
        em.setBounds(160, 180, 250, 40);

        nums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numsActionPerformed(evt);
            }
        });
        jPanel1.add(nums);
        nums.setBounds(160, 230, 250, 40);
        jPanel1.add(us);
        us.setBounds(160, 280, 250, 40);
        jPanel1.add(ps);
        ps.setBounds(160, 330, 250, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Type: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 430, 50, 30);

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jPanel1.add(type);
        type.setBounds(270, 430, 140, 30);

        label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label.setText("Label");
        label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelActionPerformed(evt);
            }
        });
        jPanel1.add(label);
        label.setBounds(190, 510, 90, 30);

        id.setEditable(false);
        id.setEnabled(false);
        jPanel1.add(id);
        id.setBounds(160, 30, 250, 40);

        stat.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        stat.setText("Status:");
        jPanel1.add(stat);
        stat.setBounds(170, 390, 48, 30);

        stats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        jPanel1.add(stats);
        stats.setBounds(270, 390, 140, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("First Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 90, 80, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Last Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 140, 80, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 190, 38, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Number:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 240, 60, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Username:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 290, 70, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Password:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 340, 70, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("ID:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 40, 17, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        close();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void numsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numsActionPerformed

    private void labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelActionPerformed
       if (Action.equals("Add")) {
        if (fn.getText().isEmpty() || ln.getText().isEmpty() || em.getText().isEmpty() || us.getText().isEmpty() || ps.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required!");
        } else if (ps.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Password must have at least 8 characters!");
            ps.setText("");
        } else if (duplicateCheck()) {
            System.out.println("Duplicate Exist");
        } else {
            try {
                
                dbConnector dbc = new dbConnector();
                String pass = passwordHasher.hashPassword(ps.getText());
           
            
            int result = dbc.insert("INSERT INTO tbl(u_fname, u_lname, u_email, u_username, u_password, Number, u_type, u_status) "
                    + "VALUES ('" + fn.getText() + "','" + ln.getText() + "','" + em.getText() + "','" + us.getText() + "','" + pass + "','" + nums.getText() + "','" + type.getSelectedItem() + "','" + stats.getSelectedItem() + "')");
            if (result == 1) {
                JOptionPane.showMessageDialog(null, "Successfully Save!");
                close();
            } else {
                System.out.println("Saving Data Failed!");
            }
            } catch (NoSuchAlgorithmException ex) {
                JOptionPane.showMessageDialog(null, "Error occurred while Saving: " + ex);
            }
        }
    } else if (Action.equals("Update")) {
        if (fn.getText().isEmpty() || ln.getText().isEmpty() || em.getText().isEmpty() || us.getText().isEmpty() || ps.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required!");
        } else if (ps.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Password must have at least 8 characters!");
            ps.setText("");
        } else if (duplicateCheck()) {
            System.out.println("Duplicate Exist");
        } else {
            try {
                
                dbConnector dbc = new dbConnector();
                String pass = passwordHasher.hashPassword(ps.getText());
                dbc.updateData("UPDATE tbl SET u_fname = '" + fn.getText() + "', u_lname = '" + ln.getText() + "', u_email = '" + em.getText() + "', u_username = '" + us.getText() + "', u_password = '" + pass  + "', Number = '" + nums.getText() + "', u_type = '" + type.getSelectedItem() + "', u_status ='" + stats.getSelectedItem() + "' WHERE u_id = '" + id.getText() + "'");
                close();
            } catch (SQLException | NoSuchAlgorithmException ex) {
                JOptionPane.showMessageDialog(null, "Error occurred while updating user: " + ex.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "No Action Selected!");
        close();
    }
    }//GEN-LAST:event_labelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField em;
    public javax.swing.JTextField fn;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton label;
    public javax.swing.JTextField ln;
    public javax.swing.JTextField nums;
    public javax.swing.JPasswordField ps;
    private javax.swing.JLabel stat;
    public javax.swing.JComboBox<String> stats;
    public javax.swing.JComboBox<String> type;
    public javax.swing.JTextField us;
    // End of variables declaration//GEN-END:variables
}
